---

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  import/extensions: 0
  import/no-named-as-default: 0
  import/no-unresolved: 0
  import/no-useless-path-segments: 0
  import/no-named-as-default-member: 0
